<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/bootstrap.min.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/animate.min.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/magnific-popup.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/fontawesome-all.min.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/flaticon.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/odometer.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/jquery-ui.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/slick.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/default.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/style.css">
<link rel="stylesheet" href="<?php echo $asset; ?>assets/css/responsive.css">